# Generated by Django 5.2.4 on 2025-07-28 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('dia_id', models.IntegerField(db_column='dia_id', primary_key=True, serialize=False)),
                ('nombre_dia', models.CharField(db_column='nombre_dia', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'DiaSemana',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('empleado_id', models.AutoField(db_column='empleado_id', primary_key=True, serialize=False)),
                ('codigo_frappe', models.SmallIntegerField(db_column='codigo_frappe', unique=True)),
                ('codigo_checador', models.SmallIntegerField(db_column='codigo_checador', unique=True)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('apellido_paterno', models.CharField(db_column='apellido_paterno', max_length=100)),
                ('apellido_materno', models.CharField(blank=True, db_column='apellido_materno', max_length=100, null=True)),
                ('tiene_horario_asignado', models.BooleanField(db_column='tiene_horario_asignado', default=False)),
            ],
            options={
                'db_table': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('horario_id', models.AutoField(db_column='horario_id', primary_key=True, serialize=False)),
                ('hora_entrada', models.TimeField(db_column='hora_entrada')),
                ('hora_salida', models.TimeField(db_column='hora_salida')),
                ('cruza_medianoche', models.BooleanField(db_column='cruza_medianoche', default=False)),
                ('descripcion_horario', models.CharField(db_column='descripcion_horario', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Horario',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('sucursal_id', models.AutoField(db_column='sucursal_id', primary_key=True, serialize=False)),
                ('nombre_sucursal', models.CharField(db_column='nombre_sucursal', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='TipoTurno',
            fields=[
                ('tipo_turno_id', models.AutoField(db_column='tipo_turno_id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'TipoTurno',
            },
        ),
        migrations.CreateModel(
            name='AsignacionHorario',
            fields=[
                ('asignacion_id', models.AutoField(db_column='asignacion_id', primary_key=True, serialize=False)),
                ('es_primera_quincena', models.BooleanField(blank=True, db_column='es_primera_quincena', null=True)),
                ('hora_entrada_especifica', models.TimeField(blank=True, db_column='hora_entrada_especifica', null=True)),
                ('hora_salida_especifica', models.TimeField(blank=True, db_column='hora_salida_especifica', null=True)),
                ('hora_salida_especifica_cruza_medianoche', models.BooleanField(db_column='hora_salida_especifica_cruza_medianoche', default=False)),
                ('comentarios', models.CharField(blank=True, db_column='comentarios', max_length=255, null=True)),
                ('dia_especifico', models.ForeignKey(blank=True, db_column='dia_especifico_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='core.diasemana')),
                ('empleado', models.ForeignKey(db_column='empleado_id', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='core.empleado')),
                ('horario', models.ForeignKey(blank=True, db_column='horario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='core.horario')),
                ('sucursal', models.ForeignKey(db_column='sucursal_id', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='core.sucursal')),
                ('tipo_turno', models.ForeignKey(blank=True, db_column='tipo_turno_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='core.tipoturno')),
            ],
            options={
                'db_table': 'AsignacionHorario',
                'indexes': [models.Index(fields=['empleado', 'dia_especifico'], name='AsignacionH_emplead_ef5ffb_idx'), models.Index(fields=['empleado', 'sucursal'], name='AsignacionH_emplead_55590e_idx'), models.Index(fields=['horario'], name='AsignacionH_horario_30f7a2_idx'), models.Index(fields=['tipo_turno'], name='AsignacionH_tipo_tu_320cb5_idx'), models.Index(fields=['dia_especifico'], name='AsignacionH_dia_esp_ea9583_idx')],
                'unique_together': {('empleado', 'sucursal', 'dia_especifico', 'es_primera_quincena')},
            },
        ),
    ]
