# Generated by Django 5.2.4 on 2025-07-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_vista_resumen_horarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenHorario',
            fields=[
                ('empleado_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('nombre_sucursal', models.CharField(max_length=100, null=True)),
                ('dia_especifico_id', models.IntegerField(null=True)),
                ('horario', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Resumen de Horario',
                'verbose_name_plural': 'Resúmenes de Horarios',
                'db_table': 'vista_resumen_horarios',
                'managed': False,
            },
        ),
    ]
