# Generated by Django 5.2.4 on 2025-07-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_resumenhorario'),
        ('core', '0004_funciones_personalizadas'),
    ]

    operations = [
    ]
