# Generated by Django 5.2.4 on 2025-07-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20250728_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaHorarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_frappe', models.SmallIntegerField()),
                ('nombre_completo', models.CharField(max_length=200)),
                ('nombre_sucursal', models.CharField(max_length=100)),
                ('Lunes', models.JSONField(null=True)),
                ('Martes', models.JSONField(null=True)),
                ('Miércoles', models.JSONField(db_column='Miércoles', null=True)),
                ('Jueves', models.JSONField(null=True)),
                ('Viernes', models.JSONField(null=True)),
                ('Sábado', models.JSONField(null=True)),
                ('Domingo', models.JSONField(null=True)),
            ],
            options={
                'db_table': None,
                'managed': False,
            },
        ),
    ]
