# Generated by Django 5.2.5 on 2025-08-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tablahorarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='contrasena',
            field=models.CharField(blank=True, db_column='contrasena', max_length=128, null=True),
        ),
    ]
