# Generated by Django 5.2.5 on 2025-08-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_empleado_contrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='contrasena',
            field=models.CharField(db_column='contrasena', max_length=128),
        ),
    ]
