# Generated by Django 5.2.5 on 2025-08-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_empleado_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, default='temp@correo.com', max_length=254, null=True),
        ),
    ]
