# Generated by Django 5.2.5 on 2025-08-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_empleado_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='email',
        ),
    ]
