# Generated by Django 5.0.7 on 2025-11-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_empleado_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, db_column='email', max_length=254, null=True, unique=True),
        ),
    ]
