# Generated by Django 5.0.7 on 2025-11-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_empleado_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='descripcion_horario',
            field=models.CharField(blank=True, db_column='descripcion_horario', max_length=100, null=True),
        ),
    ]
