# Generated by Django 5.0.7 on 2025-11-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_horario_descripcion_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto_perfil',
            field=models.ImageField(blank=True, db_column='foto_perfil', null=True, upload_to='perfiles/'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='descripcion_horario',
            field=models.CharField(db_column='descripcion_horario', default='Horario Base', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
