# Generated by Django 5.0.7 on 2025-11-21 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_empleado_foto_perfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='foto_perfil',
        ),
    ]
