# Generated by Django 5.0.7 on 2025-11-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_empleado_foto_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumenhorario',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='empleado',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_column='deleted_at', null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='deleted_by',
            field=models.CharField(blank=True, db_column='deleted_by', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='is_deleted',
            field=models.BooleanField(db_column='is_deleted', default=False),
        ),
    ]
